{
 "title": "Webvitals Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RE",
   "type": "graph",
   "description": "Real Experience",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "FCP_sum / FCP_count" }
   ]
  },
  {
   "title": "FCP",
   "type": "graph",
   "description": "First Contentful Paint",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "FCP_sum / FCP_count" }
   ]
  },
  {
   "title": "FID",
   "type": "graph",
   "description": "First Input Delay",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "FID_sum / FID_count" }
   ]
  },
  {
   "title": "CLS",
   "type": "graph",
   "description": "Cumulative Layout Shift",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "CLS_sum / CLS_count" }
   ]
  },
  {
   "title": "TTFB",
   "type": "graph",
   "description": "Time to First Byte",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "TTFB_sum / TTFB_count" }
   ]
  },
  {
   "title": "LCP",
   "type": "graph",
   "description": "Largest Contentful Paint",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "LCP_sum / LCP_count" }
   ]
  }
 ]
}